name: Deploy to EC2

on:
  push:
    branches: [ test ]  # test 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    # - name: Run tests
    #   run: |
    #     poetry run pytest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/chatstory:latest
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Docker 이미지 가져오기
          docker pull ${{ secrets.DOCKER_USERNAME }}/chatstory:latest
          
          # 기존 컨테이너 중지 및 삭제
          docker stop chatstory || true
          docker rm chatstory || true
          
          # 새 컨테이너 실행
          docker run -d \
            --name chatstory \
            -p 8000:8000 \
            --env-file .env \
            -v $(pwd)/secrets:/app/secrets \
            ${{ secrets.DOCKER_USERNAME }}/chatstory:latest 